LMS_Project/Models/LendRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace LMS_Project.Models
{
    public class LendRequest
    {
        [Key]
        public int LendId { get; set; }
        public string LendStatus { get; set; }
        public DateTime LendDate { get; set; }
        public DateTime ReturnDate { get; set; }
        public int UserId { get; set; }
        [ForeignKey("UserId")]
        public Account User { get; set; }
        public int BookId { get; set; }
        [ForeignKey("BookId")]
        public Book Book { get; set; }
        public double? FineAmount { get; set; }

    }
}

LMS_Project/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_Project.Models;
using Microsoft.AspNetCore.Http;

namespace LMS_Project.Controllers
{
    public class BooksController : Controller
    {
        private readonly LMS_ProjectContext _context;
        private readonly IAccountsRepo _accountsRepo;

        public BooksController(LMS_ProjectContext context, IAccountsRepo accountsRepo)
        {
            _context = context;
            _accountsRepo = accountsRepo;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var lMS_ProjectContext = _context.Books.Include(b => b.Author).Include(b => b.Publisher);
            return View(await lMS_ProjectContext.ToListAsync());
        }
        public async Task<IActionResult> AllBooksList(string searchstring)
        {
            var username = HttpContext.Session.GetString("username");
            var user = _accountsRepo.GetUserByName(username);

            var lMS_ProjectContext = _context.Books.Include(b => b.Author).Include(b => b.Publisher);
            if (!string.IsNullOrEmpty(searchstring))
            {
                lMS_ProjectContext = _context.Books.Where(b => b.Author.AuthorName.Contains(searchstring) ||
                                 b.Category.Contains(searchstring) ||
                                 b.BookTitle.Contains(searchstring)).Include(b => b.Author).Include(b => b.Publisher);
            }
            return View(await lMS_ProjectContext.ToListAsync());
        }


        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Authors, "AuthorId", "AuthorName");
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,BookTitle,NoOfCopies,AuthorId,PublisherId,Category,ImageUrl,IssuedBooks,IsAvailable")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "AuthorId", "AuthorId", book.AuthorId);
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherId", book.PublisherId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "AuthorId", "AuthorName", book.AuthorId);
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherName", book.PublisherId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookId,BookTitle,NoOfCopies,AuthorId,PublisherId,Category,ImageUrl,IssuedBooks,IsAvailable")] Book book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "AuthorId", "AuthorId", book.AuthorId);
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherId", book.PublisherId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookId == id);
        }
    }
}

LMS_Project/Controllers/LendRequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_Project.Models;
using Microsoft.AspNetCore.Http;

namespace LMS_Project.Controllers
{
    public class LendRequestsController : Controller
    {
        private readonly LMS_ProjectContext _context;
        private readonly IAccountsRepo _accountsRepo;
        private readonly ILendRepository _lendRepository;

        public LendRequestsController(LMS_ProjectContext context, IAccountsRepo accountsRepo, ILendRepository lendRepository)
        {
            _context = context;
            _accountsRepo = accountsRepo;
            _lendRepository = lendRepository;
        }

        // GET: LendRequests
        public async Task<IActionResult> Index()
        {
            var lMS_ProjectContext = _context.LendRequests.Where(b => b.LendStatus == "Requested").Include(l => l.Book).Include(l => l.User).OrderByDescending(b => b.LendId);
            return View(await lMS_ProjectContext.ToListAsync());
        }

        public async Task<IActionResult> LentList()
        {
            var lMS_ProjectContext = _context.LendRequests.Include(l => l.Book).Include(l => l.User).OrderByDescending(b => b.LendId);
            return View(await lMS_ProjectContext.ToListAsync());
        }

        public async Task<IActionResult> IssuedBooks()
        {
            var username = HttpContext.Session.GetString("username");
            var user = _accountsRepo.GetUserByName(username);
            var lMS_ProjectContext = _context.LendRequests.Where(b => b.LendStatus == "Approved" && b.UserId == user.UserId).Include(l => l.Book).Include(l => l.User).OrderByDescending(b => b.LendId);
            return View(await lMS_ProjectContext.ToListAsync());
        }

        public async Task<IActionResult> UserBookRecords()
        {
            var username = HttpContext.Session.GetString("username");
            var user = _accountsRepo.GetUserByName(username);
            var lMS_ProjectContext = _context.LendRequests.Where(b => b.UserId == user.UserId).Include(l => l.Book).Include(l => l.User).OrderByDescending(b => b.LendId);
            return View(await lMS_ProjectContext.ToListAsync());
        }

        public async Task<IActionResult> AllPastBooks()
        {
            var lMS_ProjectContext = _context.LendRequests.Include(l => l.Book).Include(l => l.User).OrderByDescending(b => b.LendId);
            return View(await lMS_ProjectContext.ToListAsync());
        }

        public ViewResult RequestToLend(int bookId)
        {
            var username = HttpContext.Session.GetString("username");
            var user = _accountsRepo.GetUserByName(username);
            var noofcopies = _context.Books.SingleOrDefault(b => b.BookId == bookId).NoOfCopies;
            if (noofcopies <= 0)
            {
                _context.Books.SingleOrDefault(b => b.BookId == bookId).IsAvailable = false;
                return View("RequestedError");
            }
            var alreadyrequested = _context.LendRequests.FirstOrDefault(b => b.BookId == bookId && b.UserId == user.UserId && b.LendStatus == "Requested");

            if (alreadyrequested != null && alreadyrequested.LendStatus == "Requested")
            {
                return View("AlreadyRequestError");
            }
            _context.Books.SingleOrDefault(b => b.BookId == bookId).NoOfCopies--;

            LendRequest lendRequest = new LendRequest()
            {
                LendStatus = "Requested",
                LendDate = System.DateTime.Now,
                ReturnDate = System.DateTime.Now,
                BookId = bookId,
                UserId = user.UserId,
                Book = _context.Books.SingleOrDefault(b => b.BookId == bookId),
                User = _context.Accounts.SingleOrDefault(u => u.UserId == user.UserId),
            };
            _context.LendRequests.Add(lendRequest);
            _context.SaveChanges();


            return View("Requested");
        }

        public ActionResult ApproveBook(int lendId)
        {
            LendRequest lr = _lendRepository.GetLendRequest(lendId);
            lr.LendStatus = "Approved";
            lr.ReturnDate = lr.LendDate.AddDays(40);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RejectBook(int lendId)
        {/*
            _context.LendRequests.FirstOrDefault(b => b.LendId == lendId).LendStatus = "Rejected";*/
            LendRequest lr = _lendRepository.GetLendRequest(lendId);
            lr.LendStatus = "Rejected";
            lr.ReturnDate = lr.LendDate;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ReturnBook(int lendId)
        {
            _context.LendRequests.FirstOrDefault(b => b.LendId == lendId).LendStatus = "Returned";
            _context.LendRequests.FirstOrDefault(b => b.LendId == lendId).FineAmount = 10 * (int)(DateTime.Now - _context.LendRequests.FirstOrDefault(b => b.LendId == lendId).LendDate).TotalDays;
            _context.LendRequests.FirstOrDefault(b => b.LendId == lendId).ReturnDate = DateTime.Now;
            _context.LendRequests.Where(b => b.LendId == lendId).Include(l => l.Book).Include(l => l.User).FirstOrDefault(b => b.LendId == lendId).Book.NoOfCopies++;
            _context.SaveChanges();
            return RedirectToAction("IssuedBooks");
        }

        // GET: LendRequests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lendRequest = await _context.LendRequests
                .Include(l => l.Book)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.LendId == id);
            if (lendRequest == null)
            {
                return NotFound();
            }

            return View(lendRequest);
        }

        // GET: LendRequests/Create
        public IActionResult Create()
        {
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "BookId");
            ViewData["UserId"] = new SelectList(_context.Accounts, "UserId", "Password");
            return View();
        }

        // POST: LendRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LendId,LendStatus,LendDate,ReturnDate,UserId,BookId,FineAmount")] LendRequest lendRequest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lendRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "BookId", lendRequest.BookId);
            ViewData["UserId"] = new SelectList(_context.Accounts, "UserId", "Password", lendRequest.UserId);
            return View(lendRequest);
        }

        // GET: LendRequests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lendRequest = await _context.LendRequests.FindAsync(id);
            if (lendRequest == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "BookId", lendRequest.BookId);
            ViewData["UserId"] = new SelectList(_context.Accounts, "UserId", "Password", lendRequest.UserId);
            return View(lendRequest);
        }

        // POST: LendRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LendId,LendStatus,LendDate,ReturnDate,UserId,BookId,FineAmount")] LendRequest lendRequest)
        {
            if (id != lendRequest.LendId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lendRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LendRequestExists(lendRequest.LendId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "BookId", lendRequest.BookId);
            ViewData["UserId"] = new SelectList(_context.Accounts, "UserId", "Password", lendRequest.UserId);
            return View(lendRequest);
        }

        // GET: LendRequests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lendRequest = await _context.LendRequests
                .Include(l => l.Book)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.LendId == id);
            if (lendRequest == null)
            {
                return NotFound();
            }

            return View(lendRequest);
        }

        // POST: LendRequests/Delete/5
        [HttpPost, ActionName("Delete")]

LMS_Project/Views/LendRequests/AllPastBooks.cshtml
@model IEnumerable<LMS_Project.Models.LendRequest>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .adminhead{
        text-align: center;
        margin-bottom: 1%;
    }
</style>
<div class="adminhead">
<h1>Lended Book's History</h1>
<img width="10%" height="10%" src="~/Images/imgs/books.png"/>
</div>
<table class="table">
    <thead>
    <tr>
        <th>@Html.DisplayNameFor(model => model.LendId)</th>
        <th>@Html.DisplayNameFor(model => model.User.UserName)</th>
        <th>@Html.DisplayNameFor(model => model.Book)</th>
        <th>@Html.DisplayNameFor(model => model.FineAmount)</th>
        <th>@Html.DisplayNameFor(model => model.LendStatus)</th>
    </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.LendId)</td>
                <td>@Html.DisplayFor(modelItem => item.User.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.Book.BookTitle)</td>
                <td>@Html.DisplayFor(modelItem => item.FineAmount)</td>
                <td>@Html.DisplayFor(modelItem => item.LendStatus)</td>
                
            </tr>
        }
    </tbody>
</table>

LMS_Project/Views/LendRequests/AlreadyRequestError.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<style>
center{
    font-size: 30px;
    margin-top: 10%;
}
</style>

<center>
    You have already requested this book!!! 
    <p>Browse for more <a asp-controller="Books" asp-action="AllBooksList"> books </a></p>
</center>

LMS_Project/Views/LendRequests/Create.cshtml
@model LMS_Project.Models.LendRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>LendRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LendStatus" class="control-label"></label>
                <input asp-for="LendStatus" class="form-control" />
                <span asp-validation-for="LendStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LendDate" class="control-label"></label>
                <input asp-for="LendDate" class="form-control" />
                <span asp-validation-for="LendDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class ="form-control" asp-items="ViewBag.BookId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FineAmount" class="control-label"></label>
                <input asp-for="FineAmount" class="form-control" />
                <span asp-validation-for="FineAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LMS_Project/Views/LendRequests/Delete.cshtml
@model LMS_Project.Models.LendRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LendRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LendStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LendStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LendDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LendDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FineAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FineAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.BookId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Password)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LendId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LMS_Project/Views/LendRequests/Details.cshtml
@model LMS_Project.Models.LendRequest

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>LendRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LendStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LendStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LendDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LendDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FineAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FineAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.BookId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LendId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LMS_Project/Views/LendRequests/Index.cshtml
@model IEnumerable<LMS_Project.Models.LendRequest>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .adminhead{
        text-align: center;
        margin-bottom: 1%;
    }
</style>
<div class="adminhead">
<h1>Admin's Requested Book list</h1>
<img width="10%" height="10%" src="~/Images/imgs/books.png"/>
</div>
<table class="table">
    <thead>
    <tr>
        <th>Lend ID</th>
        <th>User Name</th>
        <th>Book Name</th>
        <th>Lend Status</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.LendId)</td>
                <td>@Html.DisplayFor(modelItem => item.User.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.Book.BookTitle)</td>
                <td>@Html.DisplayFor(modelItem => item.LendStatus)</td>
                <td>
                    <form style="float:left;" asp-route-lendId="@item.LendId" asp-action="ApproveBook" asp-controller="LendRequests">
                        <input class="btn btn-success"  style="padding:2px" type="submit"  value="Approve"/>
                    </form>    
                    <form style="float:left;" asp-route-lendId="@item.LendId" asp-action="RejectBook" asp-controller="LendRequests">
                        <input class="btn btn-danger" style="padding:2px;margin-left:20%" type="submit"   value="Reject"/>
                    </form>    
            </td>
            </tr>
        }
    </tbody>
</table>

LMS_Project/Views/LendRequests/IssuedBooks.cshtml
@model IEnumerable<LMS_Project.Models.LendRequest>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<style>
    .adminhead{
        text-align: center;
        margin-bottom: 1%;
    }
</style>
<div class="adminhead">
<h1>Your Issued Books</h1>
<img width="10%" height="10%" src="~/Images/imgs/books.png"/>
</div>
<table class="table">
    <thead>
    <tr>
        <th>@Html.DisplayNameFor(model => model.LendId)</th>
        <th>Book Name</th>
        <th>@Html.DisplayNameFor(model => model.LendDate)</th>
        <th>Due Date</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.LendId)</td>
                <td>@Html.DisplayFor(modelItem => item.Book.BookTitle)</td>
                <td>@Html.DisplayFor(modelItem => item.LendDate)</td>
                <td>@Html.DisplayFor(modelItem => item.ReturnDate)</td>
                <td><form asp-action="ReturnBook" asp-controller="LendRequests" asp-route-lendId=@item.LendId>
                    <input class="btn btn-secondary" type="submit" value="Return Book"/>
                </form></td>
            </tr>
        }
    </tbody>
</table>

LMS_Project/Views/LendRequests/Requested.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<style>
center{
    font-size: 30px;
    margin-top: 10%;
}
</style>
<center >
    Your Book is requested successfully!! 
    <p>Browse for more <a asp-controller="Books" asp-action="AllBooksList"> books </a></p>
</center>

LMS_Project/Views/LendRequests/RequestedError.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<style>
center{
    font-size: 30px;
    margin-top: 10%;
}
</style>

<center>
    Sorry!!! This book is not available. 
    <p>Browse for more <a asp-controller="Books" asp-action="AllBooksList"> books </a></p>
</center>

LMS_Project/Views/LendRequests/ReturnBookMessage.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<style>
center{
    font-size: 30px;
    margin-top: 10%;
}
</style>


<center>
    Your Book is Returned Successfully!!! 
    <p>Browse for more <a asp-controller="Books" asp-action="AllBooksList"> books </a></p>
</center>

LMS_Project/Views/LendRequests/UserBookRecords.cshtml
@model IEnumerable<LMS_Project.Models.LendRequest>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<style>
    .adminhead{
        text-align: center;
        margin-bottom: 1%;
    }
</style>
<div class="adminhead">
<h1>Your All Books</h1>
<img width="10%" height="10%" src="~/Images/imgs/books.png"/>
</div>
<table class="table">
    <thead>
    <tr>
        <th>@Html.DisplayNameFor(model => model.LendId)</th>
        <th>Book Name</th>
        <th>Fine Amount</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.LendId)</td>
                <td>@Html.DisplayFor(modelItem => item.Book.BookTitle)</td>
                <td>@Html.DisplayFor(modelItem => item.FineAmount)</td>
                <td>@Html.DisplayFor(modelItem => item.LendStatus)</td>
            </tr>
        }
    </tbody>
</table>